name: Sanity Studio - Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'schemaTypes/**'

jobs:
  deploy:
    name: 'Deploy - Sanity Studio'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install NPM dependencies
        run: npm install

      - name: Deploy Sanity Studio
        run: npm run deploy
        env:
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
          SANITY_STUDIO_HOSTNAME: ${{ secrets.SANITY_STUDIO_HOSTNAME }}
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
